// Mocks generated by Mockito 5.4.6 from annotations
// in uae_topup_app/test/features/beneficiary/presentation/widgets/beneficiary_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i16;

import 'package:flutter_bloc/flutter_bloc.dart' as _i18;
import 'package:mockito/mockito.dart' as _i1;
import 'package:uae_topup_app/features/beneficiary/domain/entities/beneficiary.dart' as _i23;
import 'package:uae_topup_app/features/beneficiary/domain/usecases/add_beneficiary_usecase.dart' as _i3;
import 'package:uae_topup_app/features/beneficiary/domain/usecases/delete_beneficiary_usecase.dart' as _i4;
import 'package:uae_topup_app/features/beneficiary/domain/usecases/get_beneficiaries_usecase.dart' as _i2;
import 'package:uae_topup_app/features/beneficiary/domain/usecases/toggle_beneficiary_status_usecase.dart' as _i5;
import 'package:uae_topup_app/features/beneficiary/domain/usecases/update_beneficiary_monthly_amount_usecase.dart'
    as _i6;
import 'package:uae_topup_app/features/beneficiary/presentation/bloc/beneficiary_bloc.dart' as _i15;
import 'package:uae_topup_app/features/beneficiary/presentation/bloc/beneficiary_event.dart' as _i17;
import 'package:uae_topup_app/features/beneficiary/presentation/bloc/beneficiary_state.dart' as _i7;
import 'package:uae_topup_app/features/topup/domain/usecases/check_topup_eligibility_usecase.dart' as _i13;
import 'package:uae_topup_app/features/topup/domain/usecases/get_transactions_usecase.dart' as _i12;
import 'package:uae_topup_app/features/topup/domain/usecases/perform_topup_usecase.dart' as _i11;
import 'package:uae_topup_app/features/topup/presentation/bloc/topup_bloc.dart' as _i21;
import 'package:uae_topup_app/features/topup/presentation/bloc/topup_event.dart' as _i24;
import 'package:uae_topup_app/features/topup/presentation/bloc/topup_state.dart' as _i14;
import 'package:uae_topup_app/features/user/domain/entities/user.dart' as _i22;
import 'package:uae_topup_app/features/user/domain/usecases/get_user_usecase.dart' as _i8;
import 'package:uae_topup_app/features/user/domain/usecases/update_user_usecase.dart' as _i9;
import 'package:uae_topup_app/features/user/presentation/bloc/user_bloc.dart' as _i19;
import 'package:uae_topup_app/features/user/presentation/bloc/user_event.dart' as _i20;
import 'package:uae_topup_app/features/user/presentation/bloc/user_state.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetBeneficiariesUseCase_0 extends _i1.SmartFake implements _i2.GetBeneficiariesUseCase {
  _FakeGetBeneficiariesUseCase_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeAddBeneficiaryUseCase_1 extends _i1.SmartFake implements _i3.AddBeneficiaryUseCase {
  _FakeAddBeneficiaryUseCase_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeDeleteBeneficiaryUseCase_2 extends _i1.SmartFake implements _i4.DeleteBeneficiaryUseCase {
  _FakeDeleteBeneficiaryUseCase_2(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeToggleBeneficiaryStatusUseCase_3 extends _i1.SmartFake implements _i5.ToggleBeneficiaryStatusUseCase {
  _FakeToggleBeneficiaryStatusUseCase_3(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeUpdateBeneficiaryMonthlyAmountUseCase_4 extends _i1.SmartFake
    implements _i6.UpdateBeneficiaryMonthlyAmountUseCase {
  _FakeUpdateBeneficiaryMonthlyAmountUseCase_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBeneficiaryState_5 extends _i1.SmartFake implements _i7.BeneficiaryState {
  _FakeBeneficiaryState_5(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeGetUserUseCase_6 extends _i1.SmartFake implements _i8.GetUserUseCase {
  _FakeGetUserUseCase_6(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeUpdateUserUseCase_7 extends _i1.SmartFake implements _i9.UpdateUserUseCase {
  _FakeUpdateUserUseCase_7(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeUserState_8 extends _i1.SmartFake implements _i10.UserState {
  _FakeUserState_8(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakePerformTopupUseCase_9 extends _i1.SmartFake implements _i11.PerformTopupUseCase {
  _FakePerformTopupUseCase_9(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeGetTransactionsUseCase_10 extends _i1.SmartFake implements _i12.GetTransactionsUseCase {
  _FakeGetTransactionsUseCase_10(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeCheckTopupEligibilityUseCase_11 extends _i1.SmartFake implements _i13.CheckTopupEligibilityUseCase {
  _FakeCheckTopupEligibilityUseCase_11(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeTopupState_12 extends _i1.SmartFake implements _i14.TopupState {
  _FakeTopupState_12(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [BeneficiaryBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockBeneficiaryBloc extends _i1.Mock implements _i15.BeneficiaryBloc {
  MockBeneficiaryBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetBeneficiariesUseCase get getBeneficiariesUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#getBeneficiariesUseCase),
            returnValue: _FakeGetBeneficiariesUseCase_0(this, Invocation.getter(#getBeneficiariesUseCase)),
          )
          as _i2.GetBeneficiariesUseCase);

  @override
  _i3.AddBeneficiaryUseCase get addBeneficiaryUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#addBeneficiaryUseCase),
            returnValue: _FakeAddBeneficiaryUseCase_1(this, Invocation.getter(#addBeneficiaryUseCase)),
          )
          as _i3.AddBeneficiaryUseCase);

  @override
  _i4.DeleteBeneficiaryUseCase get deleteBeneficiaryUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#deleteBeneficiaryUseCase),
            returnValue: _FakeDeleteBeneficiaryUseCase_2(this, Invocation.getter(#deleteBeneficiaryUseCase)),
          )
          as _i4.DeleteBeneficiaryUseCase);

  @override
  _i5.ToggleBeneficiaryStatusUseCase get toggleBeneficiaryStatusUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#toggleBeneficiaryStatusUseCase),
            returnValue: _FakeToggleBeneficiaryStatusUseCase_3(
              this,
              Invocation.getter(#toggleBeneficiaryStatusUseCase),
            ),
          )
          as _i5.ToggleBeneficiaryStatusUseCase);

  @override
  _i6.UpdateBeneficiaryMonthlyAmountUseCase get updateBeneficiaryMonthlyAmountUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#updateBeneficiaryMonthlyAmountUseCase),
            returnValue: _FakeUpdateBeneficiaryMonthlyAmountUseCase_4(
              this,
              Invocation.getter(#updateBeneficiaryMonthlyAmountUseCase),
            ),
          )
          as _i6.UpdateBeneficiaryMonthlyAmountUseCase);

  @override
  _i7.BeneficiaryState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeBeneficiaryState_5(this, Invocation.getter(#state)),
          )
          as _i7.BeneficiaryState);

  @override
  _i16.Stream<_i7.BeneficiaryState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream), returnValue: _i16.Stream<_i7.BeneficiaryState>.empty())
          as _i16.Stream<_i7.BeneficiaryState>);

  @override
  bool get isClosed => (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false) as bool);

  @override
  void add(_i17.BeneficiaryEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]), returnValueForMissingStub: null);

  @override
  void onEvent(_i17.BeneficiaryEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]), returnValueForMissingStub: null);

  @override
  void emit(_i7.BeneficiaryState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]), returnValueForMissingStub: null);

  @override
  void on<E extends _i17.BeneficiaryEvent>(
    _i18.EventHandler<E, _i7.BeneficiaryState>? handler, {
    _i18.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(_i18.Transition<_i17.BeneficiaryEvent, _i7.BeneficiaryState>? transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]), returnValueForMissingStub: null);

  @override
  _i16.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void onChange(_i18.Change<_i7.BeneficiaryState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]), returnValueForMissingStub: null);

  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]), returnValueForMissingStub: null);

  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]), returnValueForMissingStub: null);
}

/// A class which mocks [UserBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserBloc extends _i1.Mock implements _i19.UserBloc {
  MockUserBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.GetUserUseCase get getUserUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#getUserUseCase),
            returnValue: _FakeGetUserUseCase_6(this, Invocation.getter(#getUserUseCase)),
          )
          as _i8.GetUserUseCase);

  @override
  _i9.UpdateUserUseCase get updateUserUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#updateUserUseCase),
            returnValue: _FakeUpdateUserUseCase_7(this, Invocation.getter(#updateUserUseCase)),
          )
          as _i9.UpdateUserUseCase);

  @override
  _i10.UserState get state =>
      (super.noSuchMethod(Invocation.getter(#state), returnValue: _FakeUserState_8(this, Invocation.getter(#state)))
          as _i10.UserState);

  @override
  _i16.Stream<_i10.UserState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream), returnValue: _i16.Stream<_i10.UserState>.empty())
          as _i16.Stream<_i10.UserState>);

  @override
  bool get isClosed => (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false) as bool);

  @override
  void add(_i20.UserEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]), returnValueForMissingStub: null);

  @override
  void onEvent(_i20.UserEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]), returnValueForMissingStub: null);

  @override
  void emit(_i10.UserState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]), returnValueForMissingStub: null);

  @override
  void on<E extends _i20.UserEvent>(
    _i18.EventHandler<E, _i10.UserState>? handler, {
    _i18.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(_i18.Transition<_i20.UserEvent, _i10.UserState>? transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]), returnValueForMissingStub: null);

  @override
  _i16.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void onChange(_i18.Change<_i10.UserState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]), returnValueForMissingStub: null);

  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]), returnValueForMissingStub: null);

  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]), returnValueForMissingStub: null);
}

/// A class which mocks [TopupBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopupBloc extends _i1.Mock implements _i21.TopupBloc {
  MockTopupBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.PerformTopupUseCase get performTopupUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#performTopupUseCase),
            returnValue: _FakePerformTopupUseCase_9(this, Invocation.getter(#performTopupUseCase)),
          )
          as _i11.PerformTopupUseCase);

  @override
  _i12.GetTransactionsUseCase get getTransactionsUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#getTransactionsUseCase),
            returnValue: _FakeGetTransactionsUseCase_10(this, Invocation.getter(#getTransactionsUseCase)),
          )
          as _i12.GetTransactionsUseCase);

  @override
  _i13.CheckTopupEligibilityUseCase get checkTopupEligibilityUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#checkTopupEligibilityUseCase),
            returnValue: _FakeCheckTopupEligibilityUseCase_11(this, Invocation.getter(#checkTopupEligibilityUseCase)),
          )
          as _i13.CheckTopupEligibilityUseCase);

  @override
  _i14.TopupState get state =>
      (super.noSuchMethod(Invocation.getter(#state), returnValue: _FakeTopupState_12(this, Invocation.getter(#state)))
          as _i14.TopupState);

  @override
  _i16.Stream<_i14.TopupState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream), returnValue: _i16.Stream<_i14.TopupState>.empty())
          as _i16.Stream<_i14.TopupState>);

  @override
  bool get isClosed => (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false) as bool);

  @override
  _i16.Future<bool> canPerformTopup({
    required _i22.User? user,
    required _i23.Beneficiary? beneficiary,
    required double? amount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#canPerformTopup, [], {#user: user, #beneficiary: beneficiary, #amount: amount}),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  void add(_i24.TopupEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]), returnValueForMissingStub: null);

  @override
  void onEvent(_i24.TopupEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]), returnValueForMissingStub: null);

  @override
  void emit(_i14.TopupState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]), returnValueForMissingStub: null);

  @override
  void on<E extends _i24.TopupEvent>(
    _i18.EventHandler<E, _i14.TopupState>? handler, {
    _i18.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(_i18.Transition<_i24.TopupEvent, _i14.TopupState>? transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]), returnValueForMissingStub: null);

  @override
  _i16.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void onChange(_i18.Change<_i14.TopupState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]), returnValueForMissingStub: null);

  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]), returnValueForMissingStub: null);

  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]), returnValueForMissingStub: null);
}
