// Mocks generated by Mockito 5.4.6 from annotations
// in uae_topup_app/test/features/beneficiary/domain/usecases/get_beneficiaries_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:uae_topup_app/features/beneficiary/domain/entities/beneficiary.dart' as _i2;
import 'package:uae_topup_app/features/beneficiary/domain/repositories/beneficiary_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBeneficiary_0 extends _i1.SmartFake implements _i2.Beneficiary {
  _FakeBeneficiary_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [BeneficiaryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBeneficiaryRepository extends _i1.Mock implements _i3.BeneficiaryRepository {
  MockBeneficiaryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Beneficiary>> getBeneficiaries() =>
      (super.noSuchMethod(
            Invocation.method(#getBeneficiaries, []),
            returnValue: _i4.Future<List<_i2.Beneficiary>>.value(<_i2.Beneficiary>[]),
          )
          as _i4.Future<List<_i2.Beneficiary>>);

  @override
  _i4.Future<_i2.Beneficiary> addBeneficiary(_i2.Beneficiary? beneficiary) =>
      (super.noSuchMethod(
            Invocation.method(#addBeneficiary, [beneficiary]),
            returnValue: _i4.Future<_i2.Beneficiary>.value(
              _FakeBeneficiary_0(this, Invocation.method(#addBeneficiary, [beneficiary])),
            ),
          )
          as _i4.Future<_i2.Beneficiary>);

  @override
  _i4.Future<void> deleteBeneficiary(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBeneficiary, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Beneficiary> updateBeneficiary(_i2.Beneficiary? beneficiary) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeneficiary, [beneficiary]),
            returnValue: _i4.Future<_i2.Beneficiary>.value(
              _FakeBeneficiary_0(this, Invocation.method(#updateBeneficiary, [beneficiary])),
            ),
          )
          as _i4.Future<_i2.Beneficiary>);

  @override
  _i4.Future<void> cacheBeneficiaries(List<_i2.Beneficiary>? beneficiaries) =>
      (super.noSuchMethod(
            Invocation.method(#cacheBeneficiaries, [beneficiaries]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Beneficiary> updateBeneficiaryMonthlyAmount(String? id, double? amount) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeneficiaryMonthlyAmount, [id, amount]),
            returnValue: _i4.Future<_i2.Beneficiary>.value(
              _FakeBeneficiary_0(this, Invocation.method(#updateBeneficiaryMonthlyAmount, [id, amount])),
            ),
          )
          as _i4.Future<_i2.Beneficiary>);
}
