// Mocks generated by Mockito 5.4.6 from annotations
// in uae_topup_app/test/features/topup/domain/usecases/check_topup_eligibility_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:uae_topup_app/features/beneficiary/domain/entities/beneficiary.dart' as _i3;
import 'package:uae_topup_app/features/beneficiary/domain/repositories/beneficiary_repository.dart' as _i6;
import 'package:uae_topup_app/features/user/domain/entities/user.dart' as _i2;
import 'package:uae_topup_app/features/user/domain/repositories/user_repository.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeBeneficiary_1 extends _i1.SmartFake implements _i3.Beneficiary {
  _FakeBeneficiary_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i4.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.User> getUser() =>
      (super.noSuchMethod(
            Invocation.method(#getUser, []),
            returnValue: _i5.Future<_i2.User>.value(_FakeUser_0(this, Invocation.method(#getUser, []))),
          )
          as _i5.Future<_i2.User>);

  @override
  _i5.Future<_i2.User> updateUser(_i2.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i5.Future<_i2.User>.value(_FakeUser_0(this, Invocation.method(#updateUser, [user]))),
          )
          as _i5.Future<_i2.User>);
}

/// A class which mocks [BeneficiaryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBeneficiaryRepository extends _i1.Mock implements _i6.BeneficiaryRepository {
  MockBeneficiaryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.Beneficiary>> getBeneficiaries() =>
      (super.noSuchMethod(
            Invocation.method(#getBeneficiaries, []),
            returnValue: _i5.Future<List<_i3.Beneficiary>>.value(<_i3.Beneficiary>[]),
          )
          as _i5.Future<List<_i3.Beneficiary>>);

  @override
  _i5.Future<_i3.Beneficiary> addBeneficiary(_i3.Beneficiary? beneficiary) =>
      (super.noSuchMethod(
            Invocation.method(#addBeneficiary, [beneficiary]),
            returnValue: _i5.Future<_i3.Beneficiary>.value(
              _FakeBeneficiary_1(this, Invocation.method(#addBeneficiary, [beneficiary])),
            ),
          )
          as _i5.Future<_i3.Beneficiary>);

  @override
  _i5.Future<void> deleteBeneficiary(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBeneficiary, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.Beneficiary> updateBeneficiary(_i3.Beneficiary? beneficiary) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeneficiary, [beneficiary]),
            returnValue: _i5.Future<_i3.Beneficiary>.value(
              _FakeBeneficiary_1(this, Invocation.method(#updateBeneficiary, [beneficiary])),
            ),
          )
          as _i5.Future<_i3.Beneficiary>);

  @override
  _i5.Future<void> cacheBeneficiaries(List<_i3.Beneficiary>? beneficiaries) =>
      (super.noSuchMethod(
            Invocation.method(#cacheBeneficiaries, [beneficiaries]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.Beneficiary> updateBeneficiaryMonthlyAmount(String? id, double? amount) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeneficiaryMonthlyAmount, [id, amount]),
            returnValue: _i5.Future<_i3.Beneficiary>.value(
              _FakeBeneficiary_1(this, Invocation.method(#updateBeneficiaryMonthlyAmount, [id, amount])),
            ),
          )
          as _i5.Future<_i3.Beneficiary>);
}
