// Mocks generated by Mockito 5.4.6 from annotations
// in uae_topup_app/test/features/topup/domain/usecases/get_transactions_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:uae_topup_app/features/topup/domain/entities/topup_transaction.dart' as _i2;
import 'package:uae_topup_app/features/topup/domain/repositories/topup_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTopupTransaction_0 extends _i1.SmartFake implements _i2.TopupTransaction {
  _FakeTopupTransaction_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [TopupRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopupRepository extends _i1.Mock implements _i3.TopupRepository {
  MockTopupRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.TopupTransaction> performTopup({required String? beneficiaryId, required double? amount}) =>
      (super.noSuchMethod(
            Invocation.method(#performTopup, [], {#beneficiaryId: beneficiaryId, #amount: amount}),
            returnValue: _i4.Future<_i2.TopupTransaction>.value(
              _FakeTopupTransaction_0(
                this,
                Invocation.method(#performTopup, [], {#beneficiaryId: beneficiaryId, #amount: amount}),
              ),
            ),
          )
          as _i4.Future<_i2.TopupTransaction>);

  @override
  _i4.Future<List<_i2.TopupTransaction>> getTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getTransactions, []),
            returnValue: _i4.Future<List<_i2.TopupTransaction>>.value(<_i2.TopupTransaction>[]),
          )
          as _i4.Future<List<_i2.TopupTransaction>>);

  @override
  _i4.Future<List<_i2.TopupTransaction>> getTransactionsByMonth(DateTime? month) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsByMonth, [month]),
            returnValue: _i4.Future<List<_i2.TopupTransaction>>.value(<_i2.TopupTransaction>[]),
          )
          as _i4.Future<List<_i2.TopupTransaction>>);

  @override
  _i4.Future<List<_i2.TopupTransaction>> getTransactionsByBeneficiary(String? beneficiaryId) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsByBeneficiary, [beneficiaryId]),
            returnValue: _i4.Future<List<_i2.TopupTransaction>>.value(<_i2.TopupTransaction>[]),
          )
          as _i4.Future<List<_i2.TopupTransaction>>);
}
