// Mocks generated by Mockito 5.4.6 from annotations
// in uae_topup_app/test/features/topup/domain/usecases/perform_topup_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:uae_topup_app/features/beneficiary/domain/entities/beneficiary.dart' as _i4;
import 'package:uae_topup_app/features/beneficiary/domain/repositories/beneficiary_repository.dart' as _i8;
import 'package:uae_topup_app/features/topup/domain/entities/topup_transaction.dart' as _i2;
import 'package:uae_topup_app/features/topup/domain/repositories/topup_repository.dart' as _i5;
import 'package:uae_topup_app/features/user/domain/entities/user.dart' as _i3;
import 'package:uae_topup_app/features/user/domain/repositories/user_repository.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTopupTransaction_0 extends _i1.SmartFake implements _i2.TopupTransaction {
  _FakeTopupTransaction_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeUser_1 extends _i1.SmartFake implements _i3.User {
  _FakeUser_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeBeneficiary_2 extends _i1.SmartFake implements _i4.Beneficiary {
  _FakeBeneficiary_2(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [TopupRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopupRepository extends _i1.Mock implements _i5.TopupRepository {
  MockTopupRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.TopupTransaction> performTopup({required String? beneficiaryId, required double? amount}) =>
      (super.noSuchMethod(
            Invocation.method(#performTopup, [], {#beneficiaryId: beneficiaryId, #amount: amount}),
            returnValue: _i6.Future<_i2.TopupTransaction>.value(
              _FakeTopupTransaction_0(
                this,
                Invocation.method(#performTopup, [], {#beneficiaryId: beneficiaryId, #amount: amount}),
              ),
            ),
          )
          as _i6.Future<_i2.TopupTransaction>);

  @override
  _i6.Future<List<_i2.TopupTransaction>> getTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getTransactions, []),
            returnValue: _i6.Future<List<_i2.TopupTransaction>>.value(<_i2.TopupTransaction>[]),
          )
          as _i6.Future<List<_i2.TopupTransaction>>);

  @override
  _i6.Future<List<_i2.TopupTransaction>> getTransactionsByMonth(DateTime? month) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsByMonth, [month]),
            returnValue: _i6.Future<List<_i2.TopupTransaction>>.value(<_i2.TopupTransaction>[]),
          )
          as _i6.Future<List<_i2.TopupTransaction>>);

  @override
  _i6.Future<List<_i2.TopupTransaction>> getTransactionsByBeneficiary(String? beneficiaryId) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsByBeneficiary, [beneficiaryId]),
            returnValue: _i6.Future<List<_i2.TopupTransaction>>.value(<_i2.TopupTransaction>[]),
          )
          as _i6.Future<List<_i2.TopupTransaction>>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i7.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.User> getUser() =>
      (super.noSuchMethod(
            Invocation.method(#getUser, []),
            returnValue: _i6.Future<_i3.User>.value(_FakeUser_1(this, Invocation.method(#getUser, []))),
          )
          as _i6.Future<_i3.User>);

  @override
  _i6.Future<_i3.User> updateUser(_i3.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i6.Future<_i3.User>.value(_FakeUser_1(this, Invocation.method(#updateUser, [user]))),
          )
          as _i6.Future<_i3.User>);
}

/// A class which mocks [BeneficiaryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBeneficiaryRepository extends _i1.Mock implements _i8.BeneficiaryRepository {
  MockBeneficiaryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i4.Beneficiary>> getBeneficiaries() =>
      (super.noSuchMethod(
            Invocation.method(#getBeneficiaries, []),
            returnValue: _i6.Future<List<_i4.Beneficiary>>.value(<_i4.Beneficiary>[]),
          )
          as _i6.Future<List<_i4.Beneficiary>>);

  @override
  _i6.Future<_i4.Beneficiary> addBeneficiary(_i4.Beneficiary? beneficiary) =>
      (super.noSuchMethod(
            Invocation.method(#addBeneficiary, [beneficiary]),
            returnValue: _i6.Future<_i4.Beneficiary>.value(
              _FakeBeneficiary_2(this, Invocation.method(#addBeneficiary, [beneficiary])),
            ),
          )
          as _i6.Future<_i4.Beneficiary>);

  @override
  _i6.Future<void> deleteBeneficiary(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBeneficiary, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.Beneficiary> updateBeneficiary(_i4.Beneficiary? beneficiary) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeneficiary, [beneficiary]),
            returnValue: _i6.Future<_i4.Beneficiary>.value(
              _FakeBeneficiary_2(this, Invocation.method(#updateBeneficiary, [beneficiary])),
            ),
          )
          as _i6.Future<_i4.Beneficiary>);

  @override
  _i6.Future<void> cacheBeneficiaries(List<_i4.Beneficiary>? beneficiaries) =>
      (super.noSuchMethod(
            Invocation.method(#cacheBeneficiaries, [beneficiaries]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.Beneficiary> updateBeneficiaryMonthlyAmount(String? id, double? amount) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeneficiaryMonthlyAmount, [id, amount]),
            returnValue: _i6.Future<_i4.Beneficiary>.value(
              _FakeBeneficiary_2(this, Invocation.method(#updateBeneficiaryMonthlyAmount, [id, amount])),
            ),
          )
          as _i6.Future<_i4.Beneficiary>);
}
