// Mocks generated by Mockito 5.4.6 from annotations
// in uae_topup_app/test/features/user/presentation/bloc/user_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:uae_topup_app/features/user/domain/entities/user.dart' as _i3;
import 'package:uae_topup_app/features/user/domain/repositories/user_repository.dart' as _i2;
import 'package:uae_topup_app/features/user/domain/usecases/get_user_usecase.dart' as _i4;
import 'package:uae_topup_app/features/user/domain/usecases/update_user_usecase.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserRepository_0 extends _i1.SmartFake implements _i2.UserRepository {
  _FakeUserRepository_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeUser_1 extends _i1.SmartFake implements _i3.User {
  _FakeUser_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [GetUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserUseCase extends _i1.Mock implements _i4.GetUserUseCase {
  MockGetUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeUserRepository_0(this, Invocation.getter(#repository)),
          )
          as _i2.UserRepository);

  @override
  _i5.Future<_i3.User> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<_i3.User>.value(_FakeUser_1(this, Invocation.method(#call, []))),
          )
          as _i5.Future<_i3.User>);
}

/// A class which mocks [UpdateUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateUserUseCase extends _i1.Mock implements _i6.UpdateUserUseCase {
  MockUpdateUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeUserRepository_0(this, Invocation.getter(#repository)),
          )
          as _i2.UserRepository);

  @override
  _i5.Future<_i3.User> call(_i3.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#call, [user]),
            returnValue: _i5.Future<_i3.User>.value(_FakeUser_1(this, Invocation.method(#call, [user]))),
          )
          as _i5.Future<_i3.User>);
}
