// Mocks generated by Mockito 5.4.6 from annotations
// in uae_topup_app/test/features/beneficiary/presentation/bloc/beneficiary_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:uae_topup_app/features/beneficiary/domain/entities/beneficiary.dart' as _i3;
import 'package:uae_topup_app/features/beneficiary/domain/repositories/beneficiary_repository.dart' as _i2;
import 'package:uae_topup_app/features/beneficiary/domain/usecases/add_beneficiary_usecase.dart' as _i6;
import 'package:uae_topup_app/features/beneficiary/domain/usecases/delete_beneficiary_usecase.dart' as _i7;
import 'package:uae_topup_app/features/beneficiary/domain/usecases/get_beneficiaries_usecase.dart' as _i4;
import 'package:uae_topup_app/features/beneficiary/domain/usecases/toggle_beneficiary_status_usecase.dart' as _i8;
import 'package:uae_topup_app/features/beneficiary/domain/usecases/update_beneficiary_monthly_amount_usecase.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBeneficiaryRepository_0 extends _i1.SmartFake implements _i2.BeneficiaryRepository {
  _FakeBeneficiaryRepository_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeBeneficiary_1 extends _i1.SmartFake implements _i3.Beneficiary {
  _FakeBeneficiary_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [GetBeneficiariesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBeneficiariesUseCase extends _i1.Mock implements _i4.GetBeneficiariesUseCase {
  MockGetBeneficiariesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BeneficiaryRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeBeneficiaryRepository_0(this, Invocation.getter(#repository)),
          )
          as _i2.BeneficiaryRepository);

  @override
  _i5.Future<List<_i3.Beneficiary>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<List<_i3.Beneficiary>>.value(<_i3.Beneficiary>[]),
          )
          as _i5.Future<List<_i3.Beneficiary>>);
}

/// A class which mocks [AddBeneficiaryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddBeneficiaryUseCase extends _i1.Mock implements _i6.AddBeneficiaryUseCase {
  MockAddBeneficiaryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BeneficiaryRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeBeneficiaryRepository_0(this, Invocation.getter(#repository)),
          )
          as _i2.BeneficiaryRepository);

  @override
  _i5.Future<_i3.Beneficiary> call({required String? phoneNumber, required String? nickname}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#phoneNumber: phoneNumber, #nickname: nickname}),
            returnValue: _i5.Future<_i3.Beneficiary>.value(
              _FakeBeneficiary_1(this, Invocation.method(#call, [], {#phoneNumber: phoneNumber, #nickname: nickname})),
            ),
          )
          as _i5.Future<_i3.Beneficiary>);
}

/// A class which mocks [DeleteBeneficiaryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteBeneficiaryUseCase extends _i1.Mock implements _i7.DeleteBeneficiaryUseCase {
  MockDeleteBeneficiaryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BeneficiaryRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeBeneficiaryRepository_0(this, Invocation.getter(#repository)),
          )
          as _i2.BeneficiaryRepository);

  @override
  _i5.Future<void> call(String? beneficiaryId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [beneficiaryId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ToggleBeneficiaryStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleBeneficiaryStatusUseCase extends _i1.Mock implements _i8.ToggleBeneficiaryStatusUseCase {
  MockToggleBeneficiaryStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BeneficiaryRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeBeneficiaryRepository_0(this, Invocation.getter(#repository)),
          )
          as _i2.BeneficiaryRepository);

  @override
  _i5.Future<_i3.Beneficiary> call({required String? beneficiaryId, required bool? activate}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#beneficiaryId: beneficiaryId, #activate: activate}),
            returnValue: _i5.Future<_i3.Beneficiary>.value(
              _FakeBeneficiary_1(
                this,
                Invocation.method(#call, [], {#beneficiaryId: beneficiaryId, #activate: activate}),
              ),
            ),
          )
          as _i5.Future<_i3.Beneficiary>);
}

/// A class which mocks [UpdateBeneficiaryMonthlyAmountUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateBeneficiaryMonthlyAmountUseCase extends _i1.Mock implements _i9.UpdateBeneficiaryMonthlyAmountUseCase {
  MockUpdateBeneficiaryMonthlyAmountUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BeneficiaryRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeBeneficiaryRepository_0(this, Invocation.getter(#repository)),
          )
          as _i2.BeneficiaryRepository);

  @override
  _i5.Future<void> call({required String? beneficiaryId, required double? amount}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#beneficiaryId: beneficiaryId, #amount: amount}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
