// Mocks generated by Mockito 5.4.6 from annotations
// in uae_topup_app/test/features/topup/presentation/bloc/topup_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:uae_topup_app/features/beneficiary/domain/entities/beneficiary.dart' as _i8;
import 'package:uae_topup_app/features/beneficiary/domain/repositories/beneficiary_repository.dart' as _i4;
import 'package:uae_topup_app/features/topup/domain/entities/topup_transaction.dart' as _i10;
import 'package:uae_topup_app/features/topup/domain/repositories/topup_repository.dart' as _i2;
import 'package:uae_topup_app/features/topup/domain/usecases/check_topup_eligibility_usecase.dart' as _i11;
import 'package:uae_topup_app/features/topup/domain/usecases/get_transactions_usecase.dart' as _i9;
import 'package:uae_topup_app/features/topup/domain/usecases/perform_topup_usecase.dart' as _i5;
import 'package:uae_topup_app/features/user/domain/entities/user.dart' as _i7;
import 'package:uae_topup_app/features/user/domain/repositories/user_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTopupRepository_0 extends _i1.SmartFake implements _i2.TopupRepository {
  _FakeTopupRepository_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeUserRepository_1 extends _i1.SmartFake implements _i3.UserRepository {
  _FakeUserRepository_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeBeneficiaryRepository_2 extends _i1.SmartFake implements _i4.BeneficiaryRepository {
  _FakeBeneficiaryRepository_2(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [PerformTopupUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPerformTopupUseCase extends _i1.Mock implements _i5.PerformTopupUseCase {
  MockPerformTopupUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TopupRepository get topupRepository =>
      (super.noSuchMethod(
            Invocation.getter(#topupRepository),
            returnValue: _FakeTopupRepository_0(this, Invocation.getter(#topupRepository)),
          )
          as _i2.TopupRepository);

  @override
  _i3.UserRepository get userRepository =>
      (super.noSuchMethod(
            Invocation.getter(#userRepository),
            returnValue: _FakeUserRepository_1(this, Invocation.getter(#userRepository)),
          )
          as _i3.UserRepository);

  @override
  _i4.BeneficiaryRepository get beneficiaryRepository =>
      (super.noSuchMethod(
            Invocation.getter(#beneficiaryRepository),
            returnValue: _FakeBeneficiaryRepository_2(this, Invocation.getter(#beneficiaryRepository)),
          )
          as _i4.BeneficiaryRepository);

  @override
  _i6.Future<void> call({required _i7.User? user, required _i8.Beneficiary? beneficiary, required double? amount}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#user: user, #beneficiary: beneficiary, #amount: amount}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [GetTransactionsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTransactionsUseCase extends _i1.Mock implements _i9.GetTransactionsUseCase {
  MockGetTransactionsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TopupRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTopupRepository_0(this, Invocation.getter(#repository)),
          )
          as _i2.TopupRepository);

  @override
  _i6.Future<List<_i10.TopupTransaction>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i6.Future<List<_i10.TopupTransaction>>.value(<_i10.TopupTransaction>[]),
          )
          as _i6.Future<List<_i10.TopupTransaction>>);

  @override
  _i6.Future<List<_i10.TopupTransaction>> getByMonth(DateTime? month) =>
      (super.noSuchMethod(
            Invocation.method(#getByMonth, [month]),
            returnValue: _i6.Future<List<_i10.TopupTransaction>>.value(<_i10.TopupTransaction>[]),
          )
          as _i6.Future<List<_i10.TopupTransaction>>);

  @override
  _i6.Future<List<_i10.TopupTransaction>> getByBeneficiary(String? beneficiaryId) =>
      (super.noSuchMethod(
            Invocation.method(#getByBeneficiary, [beneficiaryId]),
            returnValue: _i6.Future<List<_i10.TopupTransaction>>.value(<_i10.TopupTransaction>[]),
          )
          as _i6.Future<List<_i10.TopupTransaction>>);

  @override
  _i6.Future<double> getMonthlyTotalForBeneficiary({required String? beneficiaryId, required DateTime? month}) =>
      (super.noSuchMethod(
            Invocation.method(#getMonthlyTotalForBeneficiary, [], {#beneficiaryId: beneficiaryId, #month: month}),
            returnValue: _i6.Future<double>.value(0.0),
          )
          as _i6.Future<double>);

  @override
  _i6.Future<double> getMonthlyTotalForUser(DateTime? month) =>
      (super.noSuchMethod(
            Invocation.method(#getMonthlyTotalForUser, [month]),
            returnValue: _i6.Future<double>.value(0.0),
          )
          as _i6.Future<double>);
}

/// A class which mocks [CheckTopupEligibilityUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckTopupEligibilityUseCase extends _i1.Mock implements _i11.CheckTopupEligibilityUseCase {
  MockCheckTopupEligibilityUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.UserRepository get userRepository =>
      (super.noSuchMethod(
            Invocation.getter(#userRepository),
            returnValue: _FakeUserRepository_1(this, Invocation.getter(#userRepository)),
          )
          as _i3.UserRepository);

  @override
  _i4.BeneficiaryRepository get beneficiaryRepository =>
      (super.noSuchMethod(
            Invocation.getter(#beneficiaryRepository),
            returnValue: _FakeBeneficiaryRepository_2(this, Invocation.getter(#beneficiaryRepository)),
          )
          as _i4.BeneficiaryRepository);

  @override
  _i6.Future<bool> call({required _i7.User? user, required _i8.Beneficiary? beneficiary, required double? amount}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#user: user, #beneficiary: beneficiary, #amount: amount}),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}
